In [2]:
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots

In [3]:
# Import the data from CSV


# The Gini coefficient measures the inequality among the values of a frequency distribution, such as levels of income. A Gini coefficient of 0 reflects perfect equality, where all income or wealth values are the same, while a Gini coefficient of 1 (or 100%) reflects maximal inequality among values, a situation where a single individual has all the income while all others have none.
#Taken from https://www.gapminder.org/data/
gini_df = pd.read_csv("gini.csv") #Gini Coefficient (2018)
gini_dfn = gini_df.dropna()#drop na values
gini_dfni = gini_dfn.set_index('country', drop=False) #Set the country index

#Ever-partnered women and girls subjected to physical and/or sexual violence by a current or former intimate partner in the previous 12 months (% ages 15â€“49)
#Taken from https://www.gapminder.org/data/
partner_violence_df = pd.read_csv("partner_violence.csv") #World partner Violence statistics (2018)
partner_violence_dfn = partner_violence_df.dropna()#drop na values
partner_violence_dfni = partner_violence_dfn.set_index('country', drop=False)

#importing GDP figures
#Taken from https://www.gapminder.org/data/
gdp_us_inflation_adjusted_df = pd.read_csv("gdppercapita_us_inflation_adjusted.csv") #ADJUSTED GDP PER CAPITA
gdp_us_inflation_adjusted_dfn = gdp_us_inflation_adjusted_df.dropna()#drop na values
gdp_us_inflation_adjusted_dfni = gdp_us_inflation_adjusted_dfn.set_index('country', drop=False)#Set the country index



# ,drop=False
#Set Limit gini year

#gini_df = gini_df['2018']


#partner_violence_dfni

gdp_us_inflation_adjusted_dfni.index
#gdp_us_inflation_adjusted_dfni[['country'],'2000']
gini_dfni['country']

country
Afghanistan      Afghanistan
Angola                Angola
Albania              Albania
Andorra              Andorra
UAE                      UAE
                    ...
Samoa                  Samoa
Yemen                  Yemen
South Africa    South Africa
Zambia                Zambia
Zimbabwe            Zimbabwe
Name: country, Length: 197, dtype: object

In [4]:
gdp_us_inflation_adjusted_dfni.index

Index(['Argentina', 'Australia', 'Austria', 'Burundi', 'Belgium', 'Benin',
       'Burkina Faso', 'Bangladesh', 'Bahamas', 'Belize', 'Bermuda', 'Bolivia',
       'Brazil', 'Botswana', 'Central African Republic', 'Chile', 'China',
       'Cote d'Ivoire', 'Cameroon', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Colombia', 'Costa Rica', 'Denmark', 'Dominican Republic', 'Algeria',
       'Ecuador', 'Egypt', 'Spain', 'Finland', 'Fiji', 'France', 'Gabon', 'UK',
       'Ghana', 'Greece', 'Guatemala', 'Guyana', 'Honduras', 'Haiti',
       'Indonesia', 'India', 'Iran', 'Italy', 'Japan', 'Kenya', 'South Korea',
       'Lesotho', 'Luxembourg', 'Madagascar', 'Mexico', 'Malawi', 'Malaysia',
       'Niger', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal',
       'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea',
       'Puerto Rico', 'Portugal', 'Paraguay', 'Rwanda', 'Sudan', 'Senegal',
       'Singapore', 'Sierra Leone', 'Suriname', 'Sweden', 'Seychelles', 'Chad',
       'Togo', 'Thailand', 'Trinidad and Tobago', 'Turkey', 'Uruguay', 'USA',
       'St. Vincent and the Grenadines', 'South Africa', 'Zambia', 'Zimbabwe'],
      dtype='object', name='country')

#### Slicing the years 2000 to 2020

In [5]:

gini_dfnic = gini_dfni.loc[:,'2000':'2020'] #slicing required dates 2000 - 2020
gdp_us_inflation_adjusted_dfnic = gdp_us_inflation_adjusted_dfni.loc[:,'2000':'2020'] #slicing required dates 2000 - 2020

gini_dfnic2 = pd.DataFrame(gini_dfnic)

new2_df = gdp_us_inflation_adjusted_dfnic.join(gini_dfnic2, lsuffix = '_gini' , rsuffix='_gdp')
#new2_df['2011_gdp']
gdp_us_inflation_adjusted_dfnic.shape

(86, 21)

In [6]:
new2_df.shape

(86, 42)

In [7]:
gini_dfnic2.shape

(197, 21)

In [8]:
# Test View Field

gdp_us_inflation_adjusted_dfnic

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
country,,,,,,,,,,,,,,,,,,,,,
Argentina,10.7k,10.1k,8900,9580,10.3k,11.1k,11.9k,12.9k,13.2k,12.3k,...,14.2k,13.9k,14.1k,13.6k,13.8k,13.4k,13.6k,13.1k,12.7k,11.3k
Australia,45.9k,46.2k,47.5k,48.5k,50k,50.9k,51.6k,52.6k,53.4k,53.3k,...,54.1k,55.3k,55.7k,56.3k,56.7k,57.4k,57.7k,58.5k,58.9k,58.1k
Austria,38.8k,39.2k,39.6k,39.8k,40.7k,41.3k,42.5k,43.9k,44.4k,42.7k,...,44.5k,44.5k,44.3k,44.2k,44.2k,44.6k,45.3k,46.2k,46.6k,43.5k
Burundi,310,309,313,300,303,295,300,299,301,297,...,299,301,305,308,289,283,278,274,270,263
Belgium,35.7k,35.9k,36.4k,36.6k,37.8k,38.4k,39.1k,40.3k,40.2k,39k,...,39.9k,40k,40k,40.4k,41k,41.3k,41.8k,42.4k,43.1k,40.6k
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA,48.7k,48.7k,49.1k,50k,51.5k,52.8k,53.7k,54.3k,53.9k,52k,...,53.4k,54.2k,54.8k,55.7k,56.8k,57.3k,58.2k,59.6k,60.7k,58.5k
St. Vincent and the Grenadines,5060,5150,5440,5820,6080,6270,6740,7000,7070,7000,...,6710,6830,7040,7160,7390,7730,7890,8150,8210,7800
South Africa,4740,4820,4950,5050,5230,5460,5710,5950,6070,5910,...,6130,6190,6260,6250,6200,6190,6230,6250,6190,5730
Zambia,815,833,844,875,907,941,981,1030,1070,1130,...,1220,1270,1290,1310,1310,1320,1320,1330,1310,1240
Zimbabwe,1680,1690,1530,1260,1180,1110,1060,1010,825,914,...,1240,1410,1420,1410,1410,1390,1420,1460,1340,1210

In [9]:
# partner_violence_dfni.index
partner_violence_df

          country  2018
0     Afghanistan  35.0
1          Angola  25.0
2         Albania   6.0
3       Argentina   4.0
4         Armenia   5.0
..            ...   ...
161       Vanuatu  29.0
162         Samoa  18.0
163  South Africa  13.0
164        Zambia  28.0
165      Zimbabwe  18.0

[166 rows x 2 columns]

In [10]:
#gini_dfni.index

In [11]:
#TODO Make all of these indexed dataframes work with all of the other methods

In [12]:
gini_dfn.head(2)

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,Afghanistan,30.5,30.5,30.5,30.5,30.5,30.5,30.5,30.5,30.5,...,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2
1,Angola,57.7,57.7,57.7,57.7,57.7,57.7,57.7,57.7,57.7,...,52.0,52.0,52.0,52.0,52.0,52.0,52.0,52.0,52.0,52.0

In [13]:
gini_dfn['2018']

0      37.7
1      51.3
2      33.2
3      35.1
4      26.0
       ...
192    38.7
193    36.7
194    63.3
195    57.1
196    47.2
Name: 2018, Length: 197, dtype: float64

In [14]:
gini_dfns = gini_dfni['2018']
gini_mod = gini_dfni['2018']

In [15]:
gini_mod = pd.DataFrame(gini_mod)
gini_mod.head()

             2018
country
Afghanistan  37.7
Angola       51.3
Albania      33.2
Andorra      35.1
UAE          26.0

In [16]:
partner_violence_dfni.head(3)

                 country  2018
country
Afghanistan  Afghanistan  35.0
Angola            Angola  25.0
Albania          Albania   6.0

In [17]:
# new Dataframe with joined series and defined columns

new_df = partner_violence_dfni.join(gini_mod, lsuffix='_pviolence', rsuffix='_gini' )
# EVEN MORE DATAFRAMES

#new2_df = new_df.join(gdp_us_inflation_adjusted_dfnic, lsuffix = '_gini' , rsuffix='_gdp')

#new2_df = new_df.merge(gdp_us_inflation_adjusted_dfnic, suffixes = '_gdp') #Try using a for loop to resolve this, run a T test from 2000 to 2020

#new2_df.head(5)
#x = gdp_us_inflation_adjusted_dfnic.isna

gdp_us_inflation_adjusted_dfnic.head(3)
#gdp_us_inflation_adjusted_dfnic['country']

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
country,,,,,,,,,,,,,,,,,,,,,
Argentina,10.7k,10.1k,8900,9580,10.3k,11.1k,11.9k,12.9k,13.2k,12.3k,...,14.2k,13.9k,14.1k,13.6k,13.8k,13.4k,13.6k,13.1k,12.7k,11.3k
Australia,45.9k,46.2k,47.5k,48.5k,50k,50.9k,51.6k,52.6k,53.4k,53.3k,...,54.1k,55.3k,55.7k,56.3k,56.7k,57.4k,57.7k,58.5k,58.9k,58.1k
Austria,38.8k,39.2k,39.6k,39.8k,40.7k,41.3k,42.5k,43.9k,44.4k,42.7k,...,44.5k,44.5k,44.3k,44.2k,44.2k,44.6k,45.3k,46.2k,46.6k,43.5k

In [18]:
new2_df.head

<bound method NDFrame.head of                                2000_gini 2001_gini 2002_gini 2003_gini  \
country
Argentina                          10.7k     10.1k      8900      9580
Australia                          45.9k     46.2k     47.5k     48.5k
Austria                            38.8k     39.2k     39.6k     39.8k
Burundi                              310       309       313       300
Belgium                            35.7k     35.9k     36.4k     36.6k
...                                  ...       ...       ...       ...
USA                                48.7k     48.7k     49.1k       50k
St. Vincent and the Grenadines      5060      5150      5440      5820
South Africa                        4740      4820      4950      5050
Zambia                               815       833       844       875
Zimbabwe                            1680      1690      1530      1260

                               2004_gini 2005_gini 2006_gini 2007_gini  \
country
Argentina                          10.3k     11.1k     11.9k     12.9k
Australia                            50k     50.9k     51.6k     52.6k
Austria                            40.7k     41.3k     42.5k     43.9k
Burundi                              303       295       300       299
Belgium                            37.8k     38.4k     39.1k     40.3k
...                                  ...       ...       ...       ...
USA                                51.5k     52.8k     53.7k     54.3k
St. Vincent and the Grenadines      6080      6270      6740      7000
South Africa                        5230      5460      5710      5950
Zambia                               907       941       981      1030
Zimbabwe                            1180      1110      1060      1010

                               2008_gini 2009_gini  ... 2011_gdp 2012_gdp  \
country                                             ...
Argentina                          13.2k     12.3k  ...     42.6     41.3
Australia                          53.4k     53.3k  ...     34.6     34.5
Austria                            44.4k     42.7k  ...     30.8     30.5
Burundi                              301       297  ...     37.0     37.8
Belgium                            40.2k       39k  ...     28.1     27.5
...                                  ...       ...  ...      ...      ...
USA                                53.9k       52k  ...     40.9     40.9
St. Vincent and the Grenadines      7070      7000  ...     38.3     38.3
South Africa                        6070      5910  ...     63.3     63.2
Zambia                              1070      1130  ...     55.9     56.2
Zimbabwe                             825       914  ...     43.1     43.4

                               2013_gdp 2014_gdp 2015_gdp 2016_gdp 2017_gdp  \
country
Argentina                          41.0     41.6     41.8     42.0     41.1
Australia                          34.5     34.4     34.4     34.4     34.4
Austria                            30.8     30.5     30.5     30.8     29.7
Burundi                            38.6     38.9     39.0     39.0     39.0
Belgium                            27.7     28.1     27.7     27.6     27.4
...                                 ...      ...      ...      ...      ...
USA                                40.6     41.5     41.2     41.1     41.2
St. Vincent and the Grenadines     38.2     38.2     38.2     38.2     38.1
South Africa                       63.1     63.0     62.7     63.0     63.3
Zambia                             56.5     56.8     57.1     57.1     57.1
Zimbabwe                           43.5     43.7     43.9     44.1     44.3

                               2018_gdp 2019_gdp 2020_gdp
country
Argentina                          41.3     42.9     43.6
Australia                          34.4     34.4     34.4
Austria                            30.9     30.9     31.4
Burundi                            39.0     39.0     40.2
Belgium                            27.2     27.2     27.9
...                                 ...      ...      ...
USA                                41.4     41.4     42.6
St. Vincent and the Grenadines     38.1     38.1     38.1
South Africa                       63.3     63.3     64.0
Zambia                             57.1     57.1     57.9
Zimbabwe                           47.2     50.3     51.0

[86 rows x 42 columns]>

In [19]:
new_df
new_df.head

<bound method NDFrame.head of                    country  2018_pviolence  2018_gini
country
Afghanistan    Afghanistan            35.0       37.7
Angola              Angola            25.0       51.3
Albania            Albania             6.0       33.2
Argentina        Argentina             4.0       41.3
Armenia            Armenia             5.0       34.4
...                    ...             ...        ...
Vanuatu            Vanuatu            29.0       37.6
Samoa                Samoa            18.0       38.7
South Africa  South Africa            13.0       63.3
Zambia              Zambia            28.0       57.1
Zimbabwe          Zimbabwe            18.0       47.2

[166 rows x 3 columns]>

In [20]:
gdp_us_inflation_adjusted_dfni.head(5)

,country,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
country,,,,,,,,,,,,,,,,,,,,,
Argentina,Argentina,7410,7690,7500,6990,7570,8240,8060,8190,8450,...,13.9k,14.1k,13.6k,13.8k,13.4k,13.6k,13.1k,12.7k,11.3k,12.4k
Australia,Australia,19.9k,20k,19.8k,20.6k,21.7k,22.5k,22.5k,23.6k,24.4k,...,55.3k,55.7k,56.3k,56.7k,57.4k,57.7k,58.5k,58.9k,58.1k,59.3k
Austria,Austria,12.1k,12.6k,12.9k,13.4k,14.1k,14.5k,15.2k,15.5k,16.1k,...,44.5k,44.3k,44.2k,44.2k,44.6k,45.3k,46.2k,46.6k,43.5k,45.2k
Burundi,Burundi,291,245,260,265,274,277,283,314,306,...,301,305,308,289,283,278,274,270,263,261
Belgium,Belgium,11.7k,12.3k,12.9k,13.3k,14.1k,14.5k,14.8k,15.3k,15.9k,...,40k,40k,40.4k,41k,41.3k,41.8k,42.4k,43.1k,40.6k,42.9k

In [21]:
partner_violence_dfn.shape

(166, 2)

In [22]:
partner_violence_dfn.head(2)

       country  2018
0  Afghanistan  35.0
1       Angola  25.0

In [23]:
partner_violence_dfn.shape

(166, 2)

In [24]:
type(new_df)

pandas.core.frame.DataFrame

In [25]:
new_df['2018_gini']
new_df['country']

country
Afghanistan      Afghanistan
Angola                Angola
Albania              Albania
Argentina          Argentina
Armenia              Armenia
                    ...
Vanuatu              Vanuatu
Samoa                  Samoa
South Africa    South Africa
Zambia                Zambia
Zimbabwe            Zimbabwe
Name: country, Length: 166, dtype: object

# Null Hypothesis

There is no correlation between the GINI scoring of a country and the reported percentages of partner violence reported in 2018.

# The Pearson Correlation test

Pearson's correlation coefficient is the covariance of the two variables divided by the product of their standard deviations. The form of the definition involves a "product moment", that is, the mean (the first moment about the origin) of the product of the mean-adjusted random variables; hence the modifier product-moment in the name. 


In statistics, correlation or dependence is any statistical relationship, whether causal or not, between two random variables or bivariate data. Although in the broadest sense, "correlation" may indicate any type of association, in statistics it usually refers to the degree to which a pair of variables are linearly related.

In [26]:
new2_df.corr(method='pearson', numeric_only = True).style.background_gradient(cmap='viridis')

In [65]:
#new2_df['2018_gini'].corr(new2_df['2018_gdp'],method='pearson').style.background_gradient(cmap='viridis')

s1 = pd.Series(new2_df['2018_gini'])
s2 = pd.Series(new2_df['2018_gdp'])
# new2_df['2018_gdp'](method='pearson', numeric_only = True).style.background_gradient(cmap='viridis')

df11 = new2_df['2018_gini'].to_frame
df12 = new2_df['2018_gdp'].to_frame

#df11.corrwith(df12)
type(df11)

#I am attempting to use corrwith or corr extract the data from new2_df

AttributeError: 'function' object has no attribute 'corrwith'

In [43]:
new2_df.head()
new2_df.index

Index(['Argentina', 'Australia', 'Austria', 'Burundi', 'Belgium', 'Benin',
       'Burkina Faso', 'Bangladesh', 'Bahamas', 'Belize', 'Bermuda', 'Bolivia',
       'Brazil', 'Botswana', 'Central African Republic', 'Chile', 'China',
       'Cote d'Ivoire', 'Cameroon', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Colombia', 'Costa Rica', 'Denmark', 'Dominican Republic', 'Algeria',
       'Ecuador', 'Egypt', 'Spain', 'Finland', 'Fiji', 'France', 'Gabon', 'UK',
       'Ghana', 'Greece', 'Guatemala', 'Guyana', 'Honduras', 'Haiti',
       'Indonesia', 'India', 'Iran', 'Italy', 'Japan', 'Kenya', 'South Korea',
       'Lesotho', 'Luxembourg', 'Madagascar', 'Mexico', 'Malawi', 'Malaysia',
       'Niger', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal',
       'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea',
       'Puerto Rico', 'Portugal', 'Paraguay', 'Rwanda', 'Sudan', 'Senegal',
       'Singapore', 'Sierra Leone', 'Suriname', 'Sweden', 'Seychelles', 'Chad',
       'Togo', 'Thailand', 'Trinidad and Tobago', 'Turkey', 'Uruguay', 'USA',
       'St. Vincent and the Grenadines', 'South Africa', 'Zambia', 'Zimbabwe'],
      dtype='object', name='country')

In [58]:
gini_dfnic.head()
gini_dfnic.index
gini_dfnic.shape
gini_dfnic['2000']

country
Afghanistan    37.700
Angola         52.000
Albania        30.100
Andorra        36.100
UAE            32.200
                ...
Samoa          40.700
Yemen          34.900
South Africa   57.800
Zambia         45.500
Zimbabwe       41.000
Name: 2000, Length: 197, dtype: float64

In [53]:
gdp_us_inflation_adjusted_dfnic.head()
gdp_us_inflation_adjusted_dfnic.index
gdp_us_inflation_adjusted_dfnic.shape

(86, 21)

In [119]:
new2_df
new2_df['2000_gdp']
#new2_df.loc["Argentina"]
#new2_df.loc['Argentina':'Austria']

#new2_df
pd.DataFrame(new2_df['2000_gdp'])
gini_dfnic

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,...,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,38.300
Angola,52.000,50.700,49.500,48.300,47.100,46.000,44.900,43.800,42.700,43.500,...,45.100,46.000,46.800,47.700,48.500,49.400,50.300,51.300,51.300,52.100
Albania,30.100,30.900,31.700,31.400,31.000,30.600,30.400,30.200,30.000,29.700,...,29.200,29.000,31.600,34.600,32.900,33.700,33.200,33.200,33.200,33.800
Andorra,36.100,36.100,36.000,35.900,35.800,35.600,35.500,35.400,35.500,35.500,...,35.500,35.500,35.400,35.400,35.300,35.200,35.200,35.100,35.000,35.000
UAE,32.200,32.200,32.100,32.000,31.900,32.000,31.800,32.100,32.300,32.600,...,32.600,32.600,32.500,31.100,29.700,28.400,27.200,26.000,26.000,26.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Samoa,40.700,40.700,40.700,41.000,41.200,41.400,41.600,41.800,42.000,41.400,...,40.000,39.400,38.700,38.700,38.700,38.700,38.700,38.700,38.700,38.700
Yemen,34.900,34.900,34.900,34.800,34.800,34.700,34.900,35.200,35.400,35.600,...,36.000,36.300,36.500,36.700,36.700,36.700,36.700,36.700,36.700,37.500
South Africa,57.800,59.100,60.500,61.900,63.300,64.800,64.200,63.600,63.000,63.200,...,63.300,63.200,63.100,63.000,62.700,63.000,63.300,63.300,63.300,64.000
Zambia,45.500,43.700,42.100,47.800,54.300,54.500,54.600,54.900,55.100,55.400,...,55.900,56.200,56.500,56.800,57.100,57.100,57.100,57.100,57.100,57.900
Zimbabwe,41.000,41.600,42.300,42.600,43.000,43.100,43.100,43.100,43.100,43.100,...,43.100,43.400,43.500,43.700,43.900,44.100,44.300,47.200,50.300,51.000

##Attempting to use Pearson COrrelation to compare

In [126]:
#Attempting to use Pearson to correlate 2/18/2024
# gdp_us_inflation_adjusted_dfnic
# gini_dfnic
# new2_df

test_x_axis_num = pd.DataFrame(new2_df['2000_gdp'])
test_y_axis_num = pd.DataFrame(new2_df['2000_gini'])

test_x_axis_index = pd.DataFrame(gdp_us_inflation_adjusted_dfnic.loc['Argentina'])
test_y_axis_index = pd.DataFrame(gini_dfnic.loc['Argentina'])


test_x_axis_index.corrwith(test_y_axis_index,axis = 0, method='pearson', numeric_only= True)

# test_x_axis_index.corrwith(test_x_axis_index,axis = 1, method='pearson', numeric_only= True)
# pd.DataFrame(new2_df.loc['Argentina']).corrwith(pd.DataFrame(new2_df.loc['Argentina']),axis = 1, method='pearson', numeric_only= True)

Argentina   NaN
dtype: float64

In [117]:
test_x_axis
#test_y_axis

                                2000_gdp
country
Argentina                         51.100
Australia                         33.300
Austria                           28.800
Burundi                           39.900
Belgium                           33.100
...                                  ...
USA                               40.100
St. Vincent and the Grenadines    38.800
South Africa                      57.800
Zambia                            45.500
Zimbabwe                          41.000

[86 rows x 1 columns]

### GINI Score:
Gini measures inequality: How large are the income differences within a society. First imagine you line up all people in a country, ordered by income: The poorest to the left and the richest to the right. Now you walk from the left to the right asking how much money they earn every year, and you add up the number. When you reach the middle, you have counted 50% of the people, but the richest half remains. The amount of income you have added up is much less than 50% of all the money, say , maybe 20%. Maybe 10%? If there are lots of people with low incomes, you will have added maybe 15% of the money for the poorest half of the population, but if the income differences are less extreme, the 50% poorest may earn 30% of the incomes. If everybody earns the same, you would have gotten to 50% of the money, after asking 50% of the people. In that case (which never happens), the gini is zero. No inequality. The opposite extreme case (which also never happens) would be that only the richest person has any income: one guy earns all the money.  Then the gini is 1. Perfect inequality. But most countries have a gini somewhere around 0.4, in-between these two extreme examples.

### Partner Violence:
Ever-partnered women and girls subjected to physical and/or sexual violence by a current or former intimate partner in the previous 12 months (% ages 15â€“49)

In [29]:
# Set sane display perameters
pd.set_option('display.float_format', lambda x: '%.3f' %x)
gini_dfn.describe().style.format("{:,.0f}")

In [30]:
fig = px.scatter(new_df ,x = 'country', y=['2018_gini','2018_pviolence'])
fig.show()

In [31]:
fig = px.scatter(new_df ,x = 'country', y=['2018_gini','2018_pviolence'])
fig.show()

In [32]:
import scipy.stats as stats
import numpy as np
from scipy.stats import f_oneway

# T-Test

In [33]:
gini_dfnic2.head(5)

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,...,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,37.700,38.300
Angola,52.000,50.700,49.500,48.300,47.100,46.000,44.900,43.800,42.700,43.500,...,45.100,46.000,46.800,47.700,48.500,49.400,50.300,51.300,51.300,52.100
Albania,30.100,30.900,31.700,31.400,31.000,30.600,30.400,30.200,30.000,29.700,...,29.200,29.000,31.600,34.600,32.900,33.700,33.200,33.200,33.200,33.800
Andorra,36.100,36.100,36.000,35.900,35.800,35.600,35.500,35.400,35.500,35.500,...,35.500,35.500,35.400,35.400,35.300,35.200,35.200,35.100,35.000,35.000
UAE,32.200,32.200,32.100,32.000,31.900,32.000,31.800,32.100,32.300,32.600,...,32.600,32.600,32.500,31.100,29.700,28.400,27.200,26.000,26.000,26.000

In [34]:
a = new_df['2018_gini']
b = new_df['2018_pviolence']
c = gini_dfnic2


print(stats.ttest_ind(a,b))

TtestResult(statistic=30.528934038044323, pvalue=3.862082081014955e-98, df=330.0)

In [35]:

print("Ttest Results -",f"statistic: {stats.ttest_ind(a, b).statistic:.3f}, pvalue: {stats.ttest_ind(a, b).pvalue:.100f}, df: {stats.ttest_ind(a, b).df:.2f}, {stats.ttest_ind(a, b).confidence_interval(confidence_level=0.95)}")

Ttest Results - statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.00, ConfidenceInterval(low=24.900078025467888, high=28.33004245645981)

In [36]:
new_df['2018_gini_float'] = new_df['2018_gini'].astype(float)
new_df['2018_pviolence_float'] = new_df['2018_pviolence'].astype(float)

ax = new_df['2018_gini_float']
bx = new_df['2018_pviolence_float']

print(stats.ttest_ind(ax,bx))

print (ax)
ax.head(5)

TtestResult(statistic=30.528934038044323, pvalue=3.862082081014955e-98, df=330.0)
country
Afghanistan    37.700
Angola         51.300
Albania        33.200
Argentina      41.300
Armenia        34.400
                ...
Vanuatu        37.600
Samoa          38.700
South Africa   63.300
Zambia         57.100
Zimbabwe       47.200
Name: 2018_gini_float, Length: 166, dtype: float64

country
Afghanistan   37.700
Angola        51.300
Albania       33.200
Argentina     41.300
Armenia       34.400
Name: 2018_gini_float, dtype: float64

In [37]:
# attempt at a loop to test p value

#for i in range(1,len(columns)):
#    fig = plt.figure(figsize=(10,5))
#    sns.boxplot(x=st_data_2018_clean[columns[i]])
#    #print(i)

In [38]:
for columnx in c.columns:
        ax = (c['%s' %columnx] )
        #print(stats.ttest_ind(ax,b))
        print(f"statistic: {stats.ttest_ind(a, b).statistic:.3f}, pvalue: {stats.ttest_ind(a, b).pvalue:.100f}, df: {stats.ttest_ind(a, b).df:.3f}")

statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000
statistic: 30.529, pvalue: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000386, df: 330.000

In [39]:
c['2000']

country
Afghanistan    37.700
Angola         52.000
Albania        30.100
Andorra        36.100
UAE            32.200
                ...
Samoa          40.700
Yemen          34.900
South Africa   57.800
Zambia         45.500
Zimbabwe       41.000
Name: 2000, Length: 197, dtype: float64

In [40]:
f_oneway(new_df['2018_gini'],new_df['2018_pviolence'])

F_onewayResult(statistic=932.0158134992607, pvalue=3.8620820810151835e-98)

In [41]:
new2_df.head(5)

,2000_gini,2001_gini,2002_gini,2003_gini,2004_gini,2005_gini,2006_gini,2007_gini,2008_gini,2009_gini,...,2011_gdp,2012_gdp,2013_gdp,2014_gdp,2015_gdp,2016_gdp,2017_gdp,2018_gdp,2019_gdp,2020_gdp
country,,,,,,,,,,,,,,,,,,,,,
Argentina,10.7k,10.1k,8900,9580,10.3k,11.1k,11.9k,12.9k,13.2k,12.3k,...,42.600,41.300,41.000,41.600,41.800,42.000,41.100,41.300,42.900,43.600
Australia,45.9k,46.2k,47.5k,48.5k,50k,50.9k,51.6k,52.6k,53.4k,53.3k,...,34.600,34.500,34.500,34.400,34.400,34.400,34.400,34.400,34.400,34.400
Austria,38.8k,39.2k,39.6k,39.8k,40.7k,41.3k,42.5k,43.9k,44.4k,42.7k,...,30.800,30.500,30.800,30.500,30.500,30.800,29.700,30.900,30.900,31.400
Burundi,310,309,313,300,303,295,300,299,301,297,...,37.000,37.800,38.600,38.900,39.000,39.000,39.000,39.000,39.000,40.200
Belgium,35.7k,35.9k,36.4k,36.6k,37.8k,38.4k,39.1k,40.3k,40.2k,39k,...,28.100,27.500,27.700,28.100,27.700,27.600,27.400,27.200,27.200,27.900